language: ruby
script: "bundle exec rake spec cucumber"
rvm: 1.9.3
services: mongodb
notifications:
  email:
    - tobias.pfeiffer@student.hpi.uni-potsdam.de
    - james+travis-ci-broken@jamesrgifford.com
    - kh@kalonhinds.com
    - steven+travis-ci@nuclearsandwich.com
  irc: "irc.freenode.org#hacketyhack"

